apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-episode-04
  template:
    metadata:
      labels:
        app: backend-episode-04
    spec:
      containers:
      - name: backend
        image: abdullahdaniyal1234/mern-episode-04-backend:latest
        ports:
        - containerPort: 5000
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: db-claim-episode-04
---
apiVersion: v1
kind: Service
metadata:
  name: backend-episode-04
spec:
  selector:
    app: backend-episode-04
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
