apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-4-backend
  template:
    metadata:
      labels:
        app: episode-4-backend
    spec:
      containers:
        - name: backend
          image: abdullahdaniyal1234/mern-episode-04-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_DB_SECRET
              value: "mongodb+srv://abdullahdaniyal:superflies1234@cluster0.s5b7diq.mongodb.net/scd3"
---
apiVersion: v1
kind: Service
metadata:
  name: episode-4-backend
spec:
  selector:
    app: episode-4-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
