apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-4-frontend
  template:
    metadata:
      labels:
        app: episode-4-frontend
    spec:
      containers:
        - name: frontend
          image: abdullahdaniyal1234/mern-episode-04-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: episode-4-frontend
spec:
  selector:
    app: episode-4-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
