apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume-episode-04
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-episode-04"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim-episode-04
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
